### ISSUE TITLE
Firefox 57 Support In Development (with modules enabled)

### ISSUE THREAD

**Issue by thielCole** [ionic-team/ionic-pwa-toolkit#2]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When running ```npm start``` on Firefox 57, with modules enabled (in about:config) it shows that the app is disabled for this browser. I see the list of features it is testing for and the browser passes with module support enabled.

**Expected behavior:**

Expected to be able to develop in firefox 57 with module support enabled.

**Steps to reproduce:**

* Go to about:config in firefox 57 
* enable dom.moduleScripts.enable
* run the app via npm start

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by thielCole** [comment]
Just realized how early this project is. Thanks for starting this, feel free to ignore my request until y'all get farther along.

**Comment by jgw96** [comment]
Hey! So this is actually expected behavior with the latest release of Stencil. You can do `npm run dev --es5` to develop in Firefox, Edge and IE. The reason it might not be working in firefox with that flag on is the lack of custom elements support in that build of Firefox. If you use the latest firefox nightly then you will not need the --es5 flag as nightly has native support for custom elements, along with shadow dom and ES modules. Thanks for opening one of the first issues on this repo haha!

**Comment by thielCole** [comment]
Thanks! I'm following this pretty closely. Really like the stencil concept and how it will apply to PWA's.
